CREATE TABLE IF NOT EXISTS `user`(
   `id` INT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(100) NOT NULL DEFAULT '',
   `age` Integer(40) NOT NULL DEFAULT '0', 
   `sex` Integer(40) NOT NULL DEFAULT '0',
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;